spring:
  application:
    name: user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      host: localhost
      port: 6380
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
  jwt:
    secret: ${JWT_SECRET_KEY}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DISCOVERY_URL}