spring:
  application:
    name: hub

  config:
    import: classpath:./properties/env.properties

  datasource:
    url: ${POSTGRE_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: dev
        format_sql: true

  data:
    redis:
      host: redis-stack
      port: 6379
      password: ${REDIS_PASSWORD}
      database: 0

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka

naver_api_key_id: ${NAVER_API_KEY_ID}
naver_api_key: ${NAVER_API_KEY}