spring:
  application:
    name: order
  datasource:
    url: ${ORDER_POSTGRE_URL}
    username: ${ORDER_POSTGRE_USERNAME}
    password: ${ORDER_POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import:
      - classpath:./properties/.env.properties
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    com.zgzg.order: DEBUG  # Feign 클라이언트가 있는 패키지

feign:
  client:
    config:
      default: # 모든 Feign 클라이언트에 적용
        loggerLevel: full