server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/orders/**
        - id: hub
          uri: lb://hub
          predicates:
            - Path=/api/v1/hubs/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true