server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
            - Path=/api/v1/join/**, /api/v1/login
        - id: company
          uri: lb://company
          predicates:
            - Path=/api/v1/companies/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/orders/**
        - id: delivery
          uri: lb://delivery
          predicates:
            - Path=/api/v1/deliveries/**
          filters:
            - name: AuthPermissionFilter
        #로그인 필요한 요청(토큰 검증 필터 o)
        - id: user
          uri: lb://user
          predicates:
            - Path=/api/v1/logout
          filters:
            - name: AuthPermissionFilter
        - id: hub
          uri: lb://hub
          predicates:
            - Path=/api/v1/hubs/**
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: AuthPermissionFilter
  jwt:
    secret: ${JWT_SECRET_KEY}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DISCOVERY_URL}
    register-with-eureka: true
    fetch-registry: true