spring:
  application:
    name: delivery
  datasource:
    url: ${DELIVERY_POSTGRE_URL}
    username: ${DELIVERY_POSTGRE_USERNAME}
    password: ${DELIVERY_POSTGRE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import:
      - classpath:./properties/.env.properties
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/